package selfmod

const (
	REASON_DYNAMIC_MANIFEST_MISSING                = "REASON_DYNAMIC_MANIFEST_MISSING"
	REASON_DYNAMIC_MANIFEST_INVALID_JSON           = "REASON_DYNAMIC_MANIFEST_INVALID_JSON"
	REASON_DYNAMIC_MANIFEST_MISSING_REQUIRED_FIELD = "REASON_DYNAMIC_MANIFEST_MISSING_REQUIRED_FIELD"
	REASON_DYNAMIC_AUTHORITY_FIELD_FORBIDDEN       = "REASON_DYNAMIC_AUTHORITY_FIELD_FORBIDDEN"
	REASON_DYNAMIC_CAPABILITY_FORBIDDEN            = "REASON_DYNAMIC_CAPABILITY_FORBIDDEN"
	REASON_DYNAMIC_CAPABILITY_REQUIRES_APPROVAL    = "REASON_DYNAMIC_CAPABILITY_REQUIRES_APPROVAL"
	REASON_DYNAMIC_PATH_OUTSIDE_STAGING            = "REASON_DYNAMIC_PATH_OUTSIDE_STAGING"
	REASON_DYNAMIC_PATH_TRAVERSAL                  = "REASON_DYNAMIC_PATH_TRAVERSAL"
	REASON_DYNAMIC_CONTROL_CHAR                    = "REASON_DYNAMIC_CONTROL_CHAR"
	REASON_DYNAMIC_STATIC_SCAN_FAILED              = "REASON_DYNAMIC_STATIC_SCAN_FAILED"
	REASON_DYNAMIC_IMPORT_FORBIDDEN                = "REASON_DYNAMIC_IMPORT_FORBIDDEN"
	REASON_DYNAMIC_INIT_FORBIDDEN                  = "REASON_DYNAMIC_INIT_FORBIDDEN"
	REASON_DYNAMIC_NETWORK_FORBIDDEN               = "REASON_DYNAMIC_NETWORK_FORBIDDEN"
	REASON_DYNAMIC_EXEC_FORBIDDEN                  = "REASON_DYNAMIC_EXEC_FORBIDDEN"
	REASON_DYNAMIC_CREDENTIAL_ACCESS_FORBIDDEN     = "REASON_DYNAMIC_CREDENTIAL_ACCESS_FORBIDDEN"
	REASON_DYNAMIC_PROTECTED_TARGET                = "REASON_DYNAMIC_PROTECTED_TARGET"
	REASON_DYNAMIC_PROMOTION_REQUIRES_APPROVAL     = "REASON_DYNAMIC_PROMOTION_REQUIRES_APPROVAL"
)
