// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/distributed/transport.proto

package distributed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RemoteEvent wraps any bus event for network transmission
type RemoteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                        // event type name (e.g., "ProviderEvent")
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // correlation ID for tracing
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`      // milliseconds since epoch
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                  // JSON-encoded event data
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`             // unique request ID for RPC correlation
	SourceNode    string                 `protobuf:"bytes,6,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`          // originating node ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteEvent) Reset() {
	*x = RemoteEvent{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteEvent) ProtoMessage() {}

func (x *RemoteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteEvent.ProtoReflect.Descriptor instead.
func (*RemoteEvent) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RemoteEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RemoteEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *RemoteEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RemoteEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RemoteEvent) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

// ProviderEvent wire format
type ProviderEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	ProviderId    string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // "xai", "google", etc.
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                           // "init", "ready", "error"
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderEventProto) Reset() {
	*x = ProviderEventProto{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderEventProto) ProtoMessage() {}

func (x *ProviderEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderEventProto.ProtoReflect.Descriptor instead.
func (*ProviderEventProto) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderEventProto) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ProviderEventProto) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ProviderEventProto) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderEventProto) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ProviderEventProto) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ProviderHealthEvent wire format
type ProviderHealthEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	ProviderId    string                 `protobuf:"bytes,3,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Healthy       bool                   `protobuf:"varint,4,opt,name=healthy,proto3" json:"healthy,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderHealthEventProto) Reset() {
	*x = ProviderHealthEventProto{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderHealthEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderHealthEventProto) ProtoMessage() {}

func (x *ProviderHealthEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderHealthEventProto.ProtoReflect.Descriptor instead.
func (*ProviderHealthEventProto) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderHealthEventProto) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ProviderHealthEventProto) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ProviderHealthEventProto) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderHealthEventProto) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ProviderHealthEventProto) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ProviderHealthEventProto) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ProviderFailoverEvent wire format
type ProviderFailoverEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	FromProvider  string                 `protobuf:"bytes,3,opt,name=from_provider,json=fromProvider,proto3" json:"from_provider,omitempty"`
	ToProvider    string                 `protobuf:"bytes,4,opt,name=to_provider,json=toProvider,proto3" json:"to_provider,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderFailoverEventProto) Reset() {
	*x = ProviderFailoverEventProto{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderFailoverEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderFailoverEventProto) ProtoMessage() {}

func (x *ProviderFailoverEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderFailoverEventProto.ProtoReflect.Descriptor instead.
func (*ProviderFailoverEventProto) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderFailoverEventProto) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ProviderFailoverEventProto) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ProviderFailoverEventProto) GetFromProvider() string {
	if x != nil {
		return x.FromProvider
	}
	return ""
}

func (x *ProviderFailoverEventProto) GetToProvider() string {
	if x != nil {
		return x.ToProvider
	}
	return ""
}

func (x *ProviderFailoverEventProto) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ToolRequestEvent wire format
type ToolRequestEventProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId  string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TimestampMs    int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	ToolName       string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	RequestId      string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ParametersJson []byte                 `protobuf:"bytes,5,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolRequestEventProto) Reset() {
	*x = ToolRequestEventProto{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequestEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequestEventProto) ProtoMessage() {}

func (x *ToolRequestEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequestEventProto.ProtoReflect.Descriptor instead.
func (*ToolRequestEventProto) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{4}
}

func (x *ToolRequestEventProto) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ToolRequestEventProto) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ToolRequestEventProto) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolRequestEventProto) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ToolRequestEventProto) GetParametersJson() []byte {
	if x != nil {
		return x.ParametersJson
	}
	return nil
}

// ToolResultEvent wire format
type ToolResultEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultEventProto) Reset() {
	*x = ToolResultEventProto{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultEventProto) ProtoMessage() {}

func (x *ToolResultEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultEventProto.ProtoReflect.Descriptor instead.
func (*ToolResultEventProto) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{5}
}

func (x *ToolResultEventProto) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ToolResultEventProto) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *ToolResultEventProto) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolResultEventProto) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ToolResultEventProto) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResultEventProto) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ToolResultEventProto) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolResultEventProto) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// EventStoreEntry for event sourcing
type EventStoreEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	SourceNode    string                 `protobuf:"bytes,7,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	Hash          string                 `protobuf:"bytes,8,opt,name=hash,proto3" json:"hash,omitempty"` // sha256 hash for tamper detection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStoreEntry) Reset() {
	*x = EventStoreEntry{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStoreEntry) ProtoMessage() {}

func (x *EventStoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStoreEntry.ProtoReflect.Descriptor instead.
func (*EventStoreEntry) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{6}
}

func (x *EventStoreEntry) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventStoreEntry) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EventStoreEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *EventStoreEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventStoreEntry) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *EventStoreEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventStoreEntry) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *EventStoreEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// ServiceDiscoveryEntry advertises a node's capabilities
type ServiceDiscoveryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAddress   string                 `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"` // host:port
	StartedAtMs   int64                  `protobuf:"varint,3,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // ["provider_coordinator", "tool_coordinator", etc.]
	HeartbeatMs   int64                  `protobuf:"varint,5,opt,name=heartbeat_ms,json=heartbeatMs,proto3" json:"heartbeat_ms,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "unhealthy"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDiscoveryEntry) Reset() {
	*x = ServiceDiscoveryEntry{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDiscoveryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscoveryEntry) ProtoMessage() {}

func (x *ServiceDiscoveryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscoveryEntry.ProtoReflect.Descriptor instead.
func (*ServiceDiscoveryEntry) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceDiscoveryEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ServiceDiscoveryEntry) GetNodeAddress() string {
	if x != nil {
		return x.NodeAddress
	}
	return ""
}

func (x *ServiceDiscoveryEntry) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *ServiceDiscoveryEntry) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ServiceDiscoveryEntry) GetHeartbeatMs() int64 {
	if x != nil {
		return x.HeartbeatMs
	}
	return 0
}

func (x *ServiceDiscoveryEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ServiceDirectoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequesterNodeId string                 `protobuf:"bytes,1,opt,name=requester_node_id,json=requesterNodeId,proto3" json:"requester_node_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceDirectoryRequest) Reset() {
	*x = ServiceDirectoryRequest{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDirectoryRequest) ProtoMessage() {}

func (x *ServiceDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ServiceDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceDirectoryRequest) GetRequesterNodeId() string {
	if x != nil {
		return x.RequesterNodeId
	}
	return ""
}

type ServiceDirectoryResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Entries       []*ServiceDiscoveryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDirectoryResponse) Reset() {
	*x = ServiceDirectoryResponse{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDirectoryResponse) ProtoMessage() {}

func (x *ServiceDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ServiceDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceDirectoryResponse) GetEntries() []*ServiceDiscoveryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{10}
}

func (x *HealthRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_distributed_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_transport_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

var File_pkg_distributed_transport_proto protoreflect.FileDescriptor

const file_pkg_distributed_transport_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/distributed/transport.proto\x12\vdistributed\"\xc5\x01\n" +
	"\vRemoteEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x1f\n" +
	"\vsource_node\x18\x06 \x01(\tR\n" +
	"sourceNode\"\xad\x01\n" +
	"\x12ProviderEventProto\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xd4\x01\n" +
	"\x18ProviderHealthEventProto\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12\x18\n" +
	"\ahealthy\x18\x04 \x01(\bR\ahealthy\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xc4\x01\n" +
	"\x1aProviderFailoverEventProto\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12#\n" +
	"\rfrom_provider\x18\x03 \x01(\tR\ffromProvider\x12\x1f\n" +
	"\vto_provider\x18\x04 \x01(\tR\n" +
	"toProvider\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xc6\x01\n" +
	"\x15ToolRequestEventProto\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12'\n" +
	"\x0fparameters_json\x18\x05 \x01(\fR\x0eparametersJson\"\x85\x02\n" +
	"\x14ToolResultEventProto\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x06 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\"\x80\x02\n" +
	"\x0fEventStoreEntry\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1f\n" +
	"\vsource_node\x18\a \x01(\tR\n" +
	"sourceNode\x12\x12\n" +
	"\x04hash\x18\b \x01(\tR\x04hash\"\xd6\x01\n" +
	"\x15ServiceDiscoveryEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fnode_address\x18\x02 \x01(\tR\vnodeAddress\x12\"\n" +
	"\rstarted_at_ms\x18\x03 \x01(\x03R\vstartedAtMs\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12!\n" +
	"\fheartbeat_ms\x18\x05 \x01(\x03R\vheartbeatMs\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"E\n" +
	"\x17ServiceDirectoryRequest\x12*\n" +
	"\x11requester_node_id\x18\x01 \x01(\tR\x0frequesterNodeId\"X\n" +
	"\x18ServiceDirectoryResponse\x12<\n" +
	"\aentries\x18\x01 \x03(\v2\".distributed.ServiceDiscoveryEntryR\aentries\"(\n" +
	"\rHealthRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"_\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs2\xfb\x01\n" +
	"\x0eDistributedBus\x12B\n" +
	"\fPublishEvent\x12\x18.distributed.RemoteEvent\x1a\x18.distributed.RemoteEvent\x12b\n" +
	"\x13GetServiceDirectory\x12$.distributed.ServiceDirectoryRequest\x1a%.distributed.ServiceDirectoryResponse\x12A\n" +
	"\x06Health\x12\x1a.distributed.HealthRequest\x1a\x1b.distributed.HealthResponseB/Z-github.com/velariumai/gorkbot/pkg/distributedb\x06proto3"

var (
	file_pkg_distributed_transport_proto_rawDescOnce sync.Once
	file_pkg_distributed_transport_proto_rawDescData []byte
)

func file_pkg_distributed_transport_proto_rawDescGZIP() []byte {
	file_pkg_distributed_transport_proto_rawDescOnce.Do(func() {
		file_pkg_distributed_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_distributed_transport_proto_rawDesc), len(file_pkg_distributed_transport_proto_rawDesc)))
	})
	return file_pkg_distributed_transport_proto_rawDescData
}

var file_pkg_distributed_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_distributed_transport_proto_goTypes = []any{
	(*RemoteEvent)(nil),                // 0: distributed.RemoteEvent
	(*ProviderEventProto)(nil),         // 1: distributed.ProviderEventProto
	(*ProviderHealthEventProto)(nil),   // 2: distributed.ProviderHealthEventProto
	(*ProviderFailoverEventProto)(nil), // 3: distributed.ProviderFailoverEventProto
	(*ToolRequestEventProto)(nil),      // 4: distributed.ToolRequestEventProto
	(*ToolResultEventProto)(nil),       // 5: distributed.ToolResultEventProto
	(*EventStoreEntry)(nil),            // 6: distributed.EventStoreEntry
	(*ServiceDiscoveryEntry)(nil),      // 7: distributed.ServiceDiscoveryEntry
	(*ServiceDirectoryRequest)(nil),    // 8: distributed.ServiceDirectoryRequest
	(*ServiceDirectoryResponse)(nil),   // 9: distributed.ServiceDirectoryResponse
	(*HealthRequest)(nil),              // 10: distributed.HealthRequest
	(*HealthResponse)(nil),             // 11: distributed.HealthResponse
}
var file_pkg_distributed_transport_proto_depIdxs = []int32{
	7,  // 0: distributed.ServiceDirectoryResponse.entries:type_name -> distributed.ServiceDiscoveryEntry
	0,  // 1: distributed.DistributedBus.PublishEvent:input_type -> distributed.RemoteEvent
	8,  // 2: distributed.DistributedBus.GetServiceDirectory:input_type -> distributed.ServiceDirectoryRequest
	10, // 3: distributed.DistributedBus.Health:input_type -> distributed.HealthRequest
	0,  // 4: distributed.DistributedBus.PublishEvent:output_type -> distributed.RemoteEvent
	9,  // 5: distributed.DistributedBus.GetServiceDirectory:output_type -> distributed.ServiceDirectoryResponse
	11, // 6: distributed.DistributedBus.Health:output_type -> distributed.HealthResponse
	4,  // [4:7] is the sub-list for method output_type
	1,  // [1:4] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_distributed_transport_proto_init() }
func file_pkg_distributed_transport_proto_init() {
	if File_pkg_distributed_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_distributed_transport_proto_rawDesc), len(file_pkg_distributed_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_distributed_transport_proto_goTypes,
		DependencyIndexes: file_pkg_distributed_transport_proto_depIdxs,
		MessageInfos:      file_pkg_distributed_transport_proto_msgTypes,
	}.Build()
	File_pkg_distributed_transport_proto = out.File
	file_pkg_distributed_transport_proto_goTypes = nil
	file_pkg_distributed_transport_proto_depIdxs = nil
}
