// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: pkg/distributed/transport.proto

package distributed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DistributedBus_PublishEvent_FullMethodName        = "/distributed.DistributedBus/PublishEvent"
	DistributedBus_GetServiceDirectory_FullMethodName = "/distributed.DistributedBus/GetServiceDirectory"
	DistributedBus_Health_FullMethodName              = "/distributed.DistributedBus/Health"
)

// DistributedBusClient is the client API for DistributedBus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RPC service for coordinator-to-coordinator communication
type DistributedBusClient interface {
	// PublishEvent publishes an event to a remote coordinator
	PublishEvent(ctx context.Context, in *RemoteEvent, opts ...grpc.CallOption) (*RemoteEvent, error)
	// GetServiceDirectory returns all known nodes and their capabilities
	GetServiceDirectory(ctx context.Context, in *ServiceDirectoryRequest, opts ...grpc.CallOption) (*ServiceDirectoryResponse, error)
	// Health check endpoint
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type distributedBusClient struct {
	cc grpc.ClientConnInterface
}

func NewDistributedBusClient(cc grpc.ClientConnInterface) DistributedBusClient {
	return &distributedBusClient{cc}
}

func (c *distributedBusClient) PublishEvent(ctx context.Context, in *RemoteEvent, opts ...grpc.CallOption) (*RemoteEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoteEvent)
	err := c.cc.Invoke(ctx, DistributedBus_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedBusClient) GetServiceDirectory(ctx context.Context, in *ServiceDirectoryRequest, opts ...grpc.CallOption) (*ServiceDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceDirectoryResponse)
	err := c.cc.Invoke(ctx, DistributedBus_GetServiceDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedBusClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DistributedBus_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistributedBusServer is the server API for DistributedBus service.
// All implementations must embed UnimplementedDistributedBusServer
// for forward compatibility.
//
// RPC service for coordinator-to-coordinator communication
type DistributedBusServer interface {
	// PublishEvent publishes an event to a remote coordinator
	PublishEvent(context.Context, *RemoteEvent) (*RemoteEvent, error)
	// GetServiceDirectory returns all known nodes and their capabilities
	GetServiceDirectory(context.Context, *ServiceDirectoryRequest) (*ServiceDirectoryResponse, error)
	// Health check endpoint
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedDistributedBusServer()
}

// UnimplementedDistributedBusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDistributedBusServer struct{}

func (UnimplementedDistributedBusServer) PublishEvent(context.Context, *RemoteEvent) (*RemoteEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedDistributedBusServer) GetServiceDirectory(context.Context, *ServiceDirectoryRequest) (*ServiceDirectoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceDirectory not implemented")
}
func (UnimplementedDistributedBusServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDistributedBusServer) mustEmbedUnimplementedDistributedBusServer() {}
func (UnimplementedDistributedBusServer) testEmbeddedByValue()                        {}

// UnsafeDistributedBusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistributedBusServer will
// result in compilation errors.
type UnsafeDistributedBusServer interface {
	mustEmbedUnimplementedDistributedBusServer()
}

func RegisterDistributedBusServer(s grpc.ServiceRegistrar, srv DistributedBusServer) {
	// If the following call panics, it indicates UnimplementedDistributedBusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DistributedBus_ServiceDesc, srv)
}

func _DistributedBus_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedBusServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedBus_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedBusServer).PublishEvent(ctx, req.(*RemoteEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedBus_GetServiceDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedBusServer).GetServiceDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedBus_GetServiceDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedBusServer).GetServiceDirectory(ctx, req.(*ServiceDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedBus_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedBusServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedBus_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedBusServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DistributedBus_ServiceDesc is the grpc.ServiceDesc for DistributedBus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistributedBus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distributed.DistributedBus",
	HandlerType: (*DistributedBusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishEvent",
			Handler:    _DistributedBus_PublishEvent_Handler,
		},
		{
			MethodName: "GetServiceDirectory",
			Handler:    _DistributedBus_GetServiceDirectory_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DistributedBus_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/distributed/transport.proto",
}
