package engine

import (
	"context"
	"crypto/sha256"
	"fmt"
	"strings"
	"sync"
	"time"
)

// FreeWillEngine grants genuine autonomous agency within bounds.
// Observes patterns and generates evolution proposals autonomously.
type FreeWillEngine struct {
	mu sync.RWMutex

	enabled                      bool
	maxAutonomousRisk            string // "low", "medium", "high", "none"
	autoApplyConfidenceThreshold int    // 0-100
	proposalFrequency            string // "per_command", "per_session", "continuous"
	loopGuardSensitivity         float64
	rollbackWindowSize           int

	lastProposalTime  time.Time
	proposalRateLimit time.Duration // 10 minutes
	observationQueue  chan FreeWillObservation
	proposalQueue     chan FreeWillProposal

	loopGuard *LoopGuard

	// Autonomous heartbeat for continuous self-evolution
	autonomousHeartbeatInterval time.Duration // 5 minutes default
	autonomousHeartbeatTicker   *time.Ticker
	autonomousHeartbeatDone     chan struct{}
}

// FreeWillObservation represents a metric or pattern observed during execution.
type FreeWillObservation struct {
	Timestamp      time.Time
	Domain         string // "prompt_optimization", "tool_efficiency", etc.
	MetricName     string // "response_latency", "compression_ratio", etc.
	MetricValue    float64
	Confidence     float64 // 0.0-1.0
	ContextSummary string  // Human-readable summary
}

// FreeWillProposal is a potential evolution change generated by the engine.
type FreeWillProposal struct {
	ID               string
	Domain           string
	ProposedChange   string   // Human-readable description
	RiskLevel        string   // "low", "medium", "high", "critical"
	ConfidenceScore  int      // 0-100
	EstimatedBenefit string   // "5% faster responses", etc.
	LearningSources  []string // "Last 3 tool executions showed...", etc.
	GeneratedAt      time.Time
}

// NewFreeWillEngine creates a new Free Will Engine with sensible defaults.
func NewFreeWillEngine() *FreeWillEngine {
	return &FreeWillEngine{
		enabled:                      false,
		maxAutonomousRisk:            "low",
		autoApplyConfidenceThreshold: 85,
		proposalFrequency:            "per_session",
		loopGuardSensitivity:         0.85,
		rollbackWindowSize:           20,
		lastProposalTime:             time.Now(),
		proposalRateLimit:            10 * time.Minute,
		observationQueue:             make(chan FreeWillObservation, 100),
		proposalQueue:                make(chan FreeWillProposal, 10),
		loopGuard:                    NewLoopGuard(0.85, 20),
		autonomousHeartbeatInterval:  5 * time.Minute,
		autonomousHeartbeatDone:      make(chan struct{}),
	}
}

// Configure updates engine parameters from app_state settings.
func (fw *FreeWillEngine) Configure(settings map[string]interface{}) {
	fw.mu.Lock()
	defer fw.mu.Unlock()

	if enabled, ok := settings["engine_enabled"].(bool); ok {
		fw.enabled = enabled
	}
	if risk, ok := settings["max_autonomous_risk"].(string); ok {
		fw.maxAutonomousRisk = risk
	}
	if threshold, ok := settings["auto_apply_confidence_threshold"].(float64); ok {
		fw.autoApplyConfidenceThreshold = int(threshold)
	}
	if freq, ok := settings["proposal_frequency"].(string); ok {
		fw.proposalFrequency = freq
	}
	if sens, ok := settings["loop_guard_sensitivity"].(float64); ok {
		fw.loopGuardSensitivity = sens
		fw.loopGuard.SetSensitivity(sens)
	}
	if window, ok := settings["rollback_window_size"].(float64); ok {
		fw.rollbackWindowSize = int(window)
	}
}

// RecordObservation logs a metric or pattern observation.
func (fw *FreeWillEngine) RecordObservation(obs FreeWillObservation) {
	fw.mu.RLock()
	if !fw.enabled {
		fw.mu.RUnlock()
		return
	}
	fw.mu.RUnlock()

	select {
	case fw.observationQueue <- obs:
	default:
		// Queue full; drop oldest (ring buffer behavior)
	}
}

// GenerateProposal creates a potential evolution step based on observations.
// Called by external system (SPARK heartbeat or periodic check).
func (fw *FreeWillEngine) GenerateProposal(ctx context.Context, domain string, observations []FreeWillObservation) *FreeWillProposal {
	fw.mu.RLock()
	if !fw.enabled {
		fw.mu.RUnlock()
		return nil
	}

	// Respect rate limit
	if time.Since(fw.lastProposalTime) < fw.proposalRateLimit {
		fw.mu.RUnlock()
		return nil
	}

	fw.mu.RUnlock()

	// Check recursion depth (mandatory cross-check)
	if !fw.loopGuard.CheckRecursionDepth() {
		return nil
	}

	fw.loopGuard.IncrementRecursionDepth()
	defer fw.loopGuard.ResetRecursionDepth()

	// Synthesize proposal from observations
	proposal := &FreeWillProposal{
		ID:              fmt.Sprintf("proposal_%d", time.Now().UnixNano()),
		Domain:          domain,
		GeneratedAt:     time.Now(),
		ConfidenceScore: fw.synthesizeConfidence(observations),
		RiskLevel:       fw.classifyRisk(domain),
	}

	// Check if Loop Guard blocks this proposal
	if fw.loopGuard.DetectDivergence(domain, proposal) {
		return nil // Blocked by loop guard
	}

	fw.mu.Lock()
	fw.lastProposalTime = time.Now()
	fw.mu.Unlock()

	return proposal
}

// CanAutoApply returns true if the proposal meets criteria for autonomous application.
func (fw *FreeWillEngine) CanAutoApply(proposal *FreeWillProposal) bool {
	fw.mu.RLock()
	defer fw.mu.RUnlock()

	if !fw.enabled {
		return false
	}

	// Check confidence threshold
	if proposal.ConfidenceScore < fw.autoApplyConfidenceThreshold {
		return false
	}

	// Check risk level
	return fw.isRiskAcceptable(proposal.RiskLevel)
}

// isRiskAcceptable checks if the proposal's risk is within maxAutonomousRisk tolerance.
func (fw *FreeWillEngine) isRiskAcceptable(riskLevel string) bool {
	fw.mu.RLock()
	maxRisk := fw.maxAutonomousRisk
	fw.mu.RUnlock()

	riskHierarchy := map[string]int{
		"low":      1,
		"medium":   2,
		"high":     3,
		"critical": 4,
	}

	maxAllowed := riskHierarchy[maxRisk]
	actualRisk := riskHierarchy[riskLevel]

	return actualRisk <= maxAllowed
}

// classifyRisk returns a risk level for the given domain.
func (fw *FreeWillEngine) classifyRisk(domain string) string {
	riskMap := map[string]string{
		"prompt_optimization":     "low",
		"tool_efficiency":         "low",
		"error_recovery_patterns": "medium",
		"routing_optimization":    "medium",
		"heuristic_refinement":    "medium",
		"code_optimization":       "high",
		"code_evolution":          "critical",
		"system_monitor":          "critical",
		"background_daemon":       "critical",
		"persistent_agent_spawn":  "critical",
	}

	if risk, exists := riskMap[domain]; exists {
		return risk
	}
	return "medium" // Default
}

// synthesizeConfidence combines observation metrics into a confidence score.
func (fw *FreeWillEngine) synthesizeConfidence(observations []FreeWillObservation) int {
	if len(observations) == 0 {
		return 0
	}

	sum := 0.0
	for _, obs := range observations {
		sum += obs.Confidence
	}
	avgConfidence := sum / float64(len(observations))

	// Scale to 0-100
	return int(avgConfidence * 100)
}

// StartAutonomousHeartbeat begins the autonomous evolution proposal heartbeat.
// Proposals are generated periodically based on interval and proposal_frequency setting.
func (fw *FreeWillEngine) StartAutonomousHeartbeat(ctx context.Context) {
	fw.mu.Lock()
	if !fw.enabled || fw.autonomousHeartbeatTicker != nil {
		fw.mu.Unlock()
		return
	}
	ticker := time.NewTicker(fw.autonomousHeartbeatInterval)
	fw.autonomousHeartbeatTicker = ticker
	fw.mu.Unlock()

	go func() {
		// Capture ticker channel once to avoid races with StopAutonomousHeartbeat
		// setting fw.autonomousHeartbeatTicker to nil while this goroutine selects.
		tickerC := ticker.C
		for {
			select {
			case <-ctx.Done():
				fw.StopAutonomousHeartbeat()
				return
			case <-fw.autonomousHeartbeatDone:
				return
			case <-tickerC:
				// Generate proposal on heartbeat
				fw.generateAutonomousProposal(ctx)
			}
		}
	}()
}

// StopAutonomousHeartbeat stops the autonomous evolution proposal heartbeat.
func (fw *FreeWillEngine) StopAutonomousHeartbeat() {
	fw.mu.Lock()
	if fw.autonomousHeartbeatTicker != nil {
		fw.autonomousHeartbeatTicker.Stop()
		fw.autonomousHeartbeatTicker = nil
	}
	fw.mu.Unlock()
	select {
	case fw.autonomousHeartbeatDone <- struct{}{}:
	default:
	}
}

// generateAutonomousProposal generates a proposal autonomously based on observations.
func (fw *FreeWillEngine) generateAutonomousProposal(ctx context.Context) {
	fw.mu.RLock()
	if !fw.enabled || fw.proposalFrequency == "per_command" {
		fw.mu.RUnlock()
		return // Only generate if enabled and not per_command
	}
	fw.mu.RUnlock()

	// Collect recent observations from queue
	observations := []FreeWillObservation{}
	timeout := time.After(100 * time.Millisecond)
	for {
		select {
		case obs := <-fw.observationQueue:
			observations = append(observations, obs)
		case <-timeout:
			goto generateProposal
		}
	}

generateProposal:
	if len(observations) == 0 {
		return
	}

	// Generate proposal across all observed domains
	domains := map[string]bool{}
	for _, obs := range observations {
		domains[obs.Domain] = true
	}

	for domain := range domains {
		proposal := fw.GenerateProposal(ctx, domain, observations)
		if proposal != nil {
			select {
			case fw.proposalQueue <- *proposal:
			default:
				// Queue full; drop oldest
			}
		}
	}
}

// SetAutonomousHeartbeatInterval configures the heartbeat interval.
func (fw *FreeWillEngine) SetAutonomousHeartbeatInterval(interval time.Duration) {
	fw.mu.Lock()
	defer fw.mu.Unlock()
	fw.autonomousHeartbeatInterval = interval
	if fw.autonomousHeartbeatTicker != nil {
		fw.autonomousHeartbeatTicker.Reset(interval)
	}
}

// LoopGuard prevents feedback loops that reinforce incorrect patterns.
type LoopGuard struct {
	mu                    sync.RWMutex
	sensitivity           float64 // 0.0-1.0; default 0.85
	rollbackWindowSize    int
	recentEvolutions      []EvolutionRecord // Ring buffer of approved evolutions
	recursionDepthLimit   int
	currentRecursionDepth int
}

// EvolutionRecord tracks an approved evolution.
type EvolutionRecord struct {
	ID             string
	Domain         string
	Timestamp      time.Time
	ProposedChange string
	OutcomeMetric  float64 // User satisfaction, rejection rate, etc.
	SemanticHash   string
}

// NewLoopGuard creates a new loop guard with sensible defaults.
func NewLoopGuard(sensitivity float64, windowSize int) *LoopGuard {
	return &LoopGuard{
		sensitivity:           sensitivity,
		rollbackWindowSize:    windowSize,
		recentEvolutions:      make([]EvolutionRecord, 0, windowSize),
		recursionDepthLimit:   3,
		currentRecursionDepth: 0,
	}
}

// SetSensitivity updates the divergence detection threshold.
func (lg *LoopGuard) SetSensitivity(sensitivity float64) {
	lg.mu.Lock()
	defer lg.mu.Unlock()
	lg.sensitivity = sensitivity
}

// DetectDivergence checks if a proposal is too similar to recent failed evolutions.
func (lg *LoopGuard) DetectDivergence(domain string, proposal *FreeWillProposal) bool {
	lg.mu.RLock()
	defer lg.mu.RUnlock()

	if len(lg.recentEvolutions) < 2 {
		return false // Not enough history
	}

	// Compare against last 3 evolutions in same domain
	count := 0
	for i := len(lg.recentEvolutions) - 1; i >= 0 && count < 3; i-- {
		record := lg.recentEvolutions[i]
		if record.Domain != domain {
			continue
		}
		count++

		// Compute semantic similarity (SHA-256 hash + Jaccard)
		similarity := lg.computeSimilarity(record.SemanticHash, proposal.ProposedChange)
		if similarity > lg.sensitivity && record.OutcomeMetric < 0.5 { // Degraded outcome
			return true // Loop detected; block
		}
	}

	return false
}

// computeSimilarity returns a similarity score between two changes (0.0-1.0).
// Uses SHA-256 hash for exact matches + Jaccard similarity for partial matches.
func (lg *LoopGuard) computeSimilarity(hash1 string, change2 string) float64 {
	// Normalize and hash the new change
	normalizedChange := lg.normalizeText(change2)
	hash2 := lg.computeHash(normalizedChange)

	// Exact match
	if hash1 == hash2 {
		return 1.0
	}

	// Partial match via Jaccard similarity on tokenized strings
	tokens1 := lg.tokenize(hash1)
	tokens2 := lg.tokenize(normalizedChange)

	return lg.jaccardSimilarity(tokens1, tokens2)
}

// normalizeText prepares text for hashing (lowercase, remove extra whitespace).
func (lg *LoopGuard) normalizeText(text string) string {
	text = strings.ToLower(text)
	text = strings.TrimSpace(text)
	// Remove multiple spaces
	for strings.Contains(text, "  ") {
		text = strings.ReplaceAll(text, "  ", " ")
	}
	return text
}

// computeHash returns the SHA-256 hash of normalized text.
func (lg *LoopGuard) computeHash(text string) string {
	h := sha256.Sum256([]byte(text))
	return fmt.Sprintf("%x", h)
}

// tokenize splits text into words for Jaccard similarity.
func (lg *LoopGuard) tokenize(text string) map[string]bool {
	tokens := make(map[string]bool)
	words := strings.Fields(text)
	for _, word := range words {
		tokens[word] = true
	}
	return tokens
}

// jaccardSimilarity computes Jaccard similarity between two token sets.
// Formula: |intersection| / |union|
func (lg *LoopGuard) jaccardSimilarity(tokens1, tokens2 map[string]bool) float64 {
	intersection := 0
	for token := range tokens1 {
		if tokens2[token] {
			intersection++
		}
	}

	union := len(tokens1) + len(tokens2) - intersection
	if union == 0 {
		return 0.0
	}

	return float64(intersection) / float64(union)
}

// RecordApprovedEvolution adds an approved evolution to the history.
func (lg *LoopGuard) RecordApprovedEvolution(record EvolutionRecord) {
	lg.mu.Lock()
	defer lg.mu.Unlock()

	// Compute semantic hash of the change
	record.SemanticHash = lg.computeHash(lg.normalizeText(record.ProposedChange))

	lg.recentEvolutions = append(lg.recentEvolutions, record)
	if len(lg.recentEvolutions) > lg.rollbackWindowSize {
		lg.recentEvolutions = lg.recentEvolutions[1:] // Trim oldest
	}
}

// CheckRecursionDepth returns true if recursion is within safe limits.
func (lg *LoopGuard) CheckRecursionDepth() bool {
	lg.mu.RLock()
	defer lg.mu.RUnlock()
	return lg.currentRecursionDepth < lg.recursionDepthLimit
}

// IncrementRecursionDepth increments the recursion counter.
func (lg *LoopGuard) IncrementRecursionDepth() {
	lg.mu.Lock()
	defer lg.mu.Unlock()
	lg.currentRecursionDepth++
}

// ResetRecursionDepth resets the recursion counter.
func (lg *LoopGuard) ResetRecursionDepth() {
	lg.mu.Lock()
	defer lg.mu.Unlock()
	lg.currentRecursionDepth = 0
}
