package governance

import "strings"

// Mode controls governance behavior.
type Mode string

const (
	GOVERNANCE_OFF         Mode = "GOVERNANCE_OFF"
	GOVERNANCE_AUDIT       Mode = "GOVERNANCE_AUDIT"
	GOVERNANCE_FAST        Mode = "GOVERNANCE_FAST"
	GOVERNANCE_ENFORCE     Mode = "GOVERNANCE_ENFORCE"
	GOVERNANCE_CORRECTNESS Mode = "GOVERNANCE_CORRECTNESS"
)

const (
	GOVERNANCE_ALLOWED        = "GOVERNANCE_ALLOWED"
	GOVERNANCE_BLOCKED        = "GOVERNANCE_BLOCKED"
	GOVERNANCE_AUDIT_ONLY     = "GOVERNANCE_AUDIT_ONLY"
	GOVERNANCE_REQUIRES_HUMAN = "GOVERNANCE_REQUIRES_HUMAN"
	GOVERNANCE_DEGRADED       = "GOVERNANCE_DEGRADED"
)

const (
	REASON_FAST_PATH_READ_ONLY                    = "REASON_FAST_PATH_READ_ONLY"
	REASON_AUDIT_MODE                             = "REASON_AUDIT_MODE"
	REASON_POLICY_ALLOWED                         = "REASON_POLICY_ALLOWED"
	REASON_POLICY_BLOCKED                         = "REASON_POLICY_BLOCKED"
	REASON_VCSE_UNAVAILABLE                       = "REASON_VCSE_UNAVAILABLE"
	REASON_VCSE_TIMEOUT                           = "REASON_VCSE_TIMEOUT"
	REASON_UNKNOWN_RISK                           = "REASON_UNKNOWN_RISK"
	REASON_REPEATED_ACTION_NO_STATE_PROGRESS      = "REASON_REPEATED_ACTION_NO_STATE_PROGRESS"
	REASON_EXTERNAL_SIDE_EFFECT_REQUIRES_APPROVAL = "REASON_EXTERNAL_SIDE_EFFECT_REQUIRES_APPROVAL"
	REASON_DESTRUCTIVE_REQUIRES_APPROVAL          = "REASON_DESTRUCTIVE_REQUIRES_APPROVAL"
	REASON_SELF_MODIFICATION_REQUIRES_MANIFEST    = "REASON_SELF_MODIFICATION_REQUIRES_MANIFEST"
	REASON_HUMAN_APPROVAL_GRANTED                 = "REASON_HUMAN_APPROVAL_GRANTED"
	REASON_HUMAN_APPROVAL_DENIED                  = "REASON_HUMAN_APPROVAL_DENIED"
	REASON_HUMAN_APPROVAL_TIMEOUT                 = "REASON_HUMAN_APPROVAL_TIMEOUT"
	REASON_HUMAN_APPROVAL_CANCELLED               = "REASON_HUMAN_APPROVAL_CANCELLED"
	REASON_HUMAN_APPROVAL_UNAVAILABLE             = "REASON_HUMAN_APPROVAL_UNAVAILABLE"
	REASON_APPROVAL_RUNTIME_SHUTDOWN              = "REASON_APPROVAL_RUNTIME_SHUTDOWN"
	REASON_APPROVAL_INFLIGHT_LIMIT                = "REASON_APPROVAL_INFLIGHT_LIMIT"
	REASON_APPROVAL_DUPLICATE_JOINED              = "REASON_APPROVAL_DUPLICATE_JOINED"
)

// ParseMode parses CLI mode strings.
func ParseMode(raw string) (Mode, bool) {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case "off":
		return GOVERNANCE_OFF, true
	case "audit":
		return GOVERNANCE_AUDIT, true
	case "fast":
		return GOVERNANCE_FAST, true
	case "enforce":
		return GOVERNANCE_ENFORCE, true
	case "correctness":
		return GOVERNANCE_CORRECTNESS, true
	default:
		return "", false
	}
}
